# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=['.', 'AQ_lib/AQ_Devices',
                'AQ_lib/AQ_Devices/DeviceModels',
                'AQ_lib/AQ_Devices/SystemLibrary',
                'AQ_lib/AQ_Devices/DeviceItems',
                'AQ_lib/AQ_other',
                'AQ_lib/AQ_session',
                'AQ_lib/AqWatchList',
                'AQ_lib/AQ_window_templates',
                'AQ_lib/AqWindows/AqMainWindow/',
                'AQ_lib/AqWindows/AqDeviceParamWindow',
                'AQ_lib/AqWindows/AqDeviceInfoWindow',
                'AQ_lib/AqWindows/AqWatchListWindow',
                'AQ_lib/AqWindows/AqAddDeviceWindow',
                'AQ_lib/AqWindows/AqRtcWindow',
                'AQ_lib/AqWindows/AqSetSlaveIdWindow',
                'UI',
                'UI/forms',
                'Custom_Widgets',
                'Custom_Widgets/Qss'],
    binaries=[],
    datas=[('Icons', 'Icons'),
            ('110_device_conf', '110_device_conf'),
            ('UI/icons', 'UI/icons'),
            ('jsonstyles', 'jsonstyles')],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    icon='Icons/AQico_silver.ico',
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.zipfiles,
    [],
    exclude_binaries=True,
    name='AQteckModules',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    proto_csrf=False,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='Icons/AQico_silver.ico',
)
coll = COLLECT(
    exe,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='AQteckModules',
)
